name: Automatisation des tests DevSecOps

on: 
  push:
  pull_request:

jobs:
  Dependances:
    name: Vérification requirements.txt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérifier la présence de requirements.txt
        run: |
          if [ ! -f "requirements.txt" ]; then
            echo " requirements.txt manquant !"
            exit 1
          fi
          echo " requirements.txt trouvé"

      - name: Tester l'installation des dépendances (venv)
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          echo " Dépendances installées avec succès"

  Dockerfile:
    name: Vérification Dockerfile
    runs-on: ubuntu-latest
    needs: Dependances

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérifier la présence du Dockerfile
        run: |
          if [ ! -f "Dockerfile" ]; then
            echo " Dockerfile manquant !"
            exit 1
          fi
          echo " Dockerfile trouvé"

      - name: Tester le build du Dockerfile
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t breakableflask-test:ci .
          echo " Build Docker terminé"

  Deploy:
    name: Déploiement Docker
    runs-on: ubuntu-latest
    needs: Dockerfile

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push de l'image Docker
        run: |
          docker tag breakableflask-local:ci ${{ secrets.DOCKER_USERNAME }}/breakableflask:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/breakableflask:latest
          echo " Déploiement Docker terminé"
